# Generated by Django 5.2.6 on 2025-10-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='NG', help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
    ]
